name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'
    - cron: '00 14 * * *'
    - cron: '00 06 * * 1-5'

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Node.js and npm
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'
      
      - name: Install Newman and HTML Extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run: |
          newman run "Inwarranty-flow Collection.postman_collection.json" \
          -e "QA.postman_environment.json" \
          -d "testdata.csv" \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html
      
      - name : Newman Report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
           server_address:  smpt.gmail.com
           server_port: 465
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
           subject: Phoenix Inwarranty Flow Test Excecution Notification
           to: zitenram@gmail.com
           from: ${{ secrets.EMAIL_USERNAME }}
           body: |
                 Hi,
                 Phoenix Inwarranty flow test has been executed. The Report has been published and the URL
                 is: https://zeetkumar.github.io/Phoenix-Inwarranty-Flow/
           
           
