name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'
    - cron: '00 14 * * *'
    - cron: '00 06 * * 1-5'

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Node.js and npm
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'
      
      - name: Install Newman and HTML Extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run: |
          newman run "Inwarranty-flow Collection.postman_collection.json" \
          -e "QA.postman_environment.json" \
          -d "testdata.csv" \
          -r cli,htmlextra
